"""Markdown views of the YAML KB (kb.views). Generated — never edit the views by hand."""
from __future__ import annotations

from pathlib import Path

from .store import load_kb

HEADER = "<!-- generated by `wgu kb render` from {src} — do not edit; edit the YAML and re-render -->\n\n"
RULE_LABELS = [("when", "Kiedy"), ("effect", "Skutek"), ("exceptions", "Wyjątki / nadpisania"), ("see", "Odwołania"),
               ("notes", "Uwagi")]


def _bullet(label, text):
    text = str(text).strip()
    lines = text.splitlines()
    return f"- **{label}:** {lines[0]}\n" + "".join(f"  {l}\n" for l in lines[1:]) if lines else ""


def rule_md(r: dict) -> str:
    out = f"### {r['id']} {r['title']}\n"
    if r.get("source"):
        out += _bullet("Źródło", r["source"].get("text", ""))
    for k, label in RULE_LABELS:
        if r.get(k):
            out += _bullet(label, r[k])
    if r.get("keywords"):
        out += _bullet("Słowa kluczowe", ", ".join(r["keywords"]))
    for k, v in (r.get("extra") or {}).items():
        out += _bullet(k, v)
    if r.get("body"):
        out += r["body"] + "\n"
    return out


def term_row(t):
    return f"| {t.get('en', '')} | {t.get('pl', '')} | {t.get('kind', '')} | {t.get('definition', '')} | {t.get('defined_at', '')} | {t.get('used_in', '')} |"


def table_md(t):
    out = f"## {t['id']} {t['title']}\n"
    for b in t.get("tables", []):
        out += "| " + " | ".join(b["columns"]) + " |\n|" + "---|" * len(b["columns"]) + "\n"
        out += "".join("| " + " | ".join(r) + " |\n" for r in b["rows"])
    if t.get("notes"):
        out += t["notes"] + "\n"
    return out


def proc_md(p, level=2):
    out = f"{'#' * level} {p['id']} {p['title']}\n"
    for s in p.get("steps", []):
        n = s["n"]
        out += (f"- {s['text']}\n" if n.endswith("*") else f"{n}. {s['text']}\n")
    if p.get("notes"):
        out += p["notes"] + "\n"
    for sp in p.get("subprocedures", []):
        out += "\n" + proc_md(sp, level + 1)
    return out


AMB_LABELS = [("quotes", "Cytaty"), ("description", "Opis"), ("readings", "Warianty"), ("recommendation", "Rekomendacja"),
              ("impact", "Skutek"), ("resolution_source", "Co rozstrzyga"), ("resolution", "Rozstrzygnięcie")]


def amb_md(a):
    out = f"### {a['id']} {a['title']}\n"
    for k, label in AMB_LABELS:
        if a.get(k):
            out += _bullet(label, a[k])
    for k, v in (a.get("extra") or {}).items():
        out += _bullet(k, v)
    if a.get("body"):
        out += a["body"] + "\n"
    meta = ", ".join(x for x in [a.get("status"), a.get("strength")] if x)
    return out + (f"- *status: {meta}*\n" if meta else "")


def scen_md(q):
    return f"### {q['id']} {q['question']}\n**Odp.:** {q.get('answer', '')}\n**Łańcuch:** {q.get('chain', '')}\n"


def aid_md(a):
    out = f"# {a.get('header') or a['id'] + ' ' + a['title']}\n"
    meta = [("Typ", "type"), ("Format", "format"), ("Priorytet", "priority"), ("Złożoność", "complexity")]
    out += "- " + " · ".join(f"{l}: {a[k]}" for l, k in meta if a.get(k) is not None) + "\n"
    if a.get("use_moment"):
        out += f"- Moment użycia: {a['use_moment']}\n"
    if a.get("sources"):
        out += f"- Reguły źródłowe: {a['sources']}\n"
    secs = dict(a.get("sections") or {})
    if "Cel" in secs:
        out += f"\n## Cel\n{secs.pop('Cel')}\n"
    if a.get("nodes"):
        out += "\n## Węzły\n| ID | Kształt | Tekst | Reguła |\n|---|---|---|---|\n"
        out += "".join(f"| {n['id']} | {n['shape']} | {n['text']} | {n.get('rules', '')} |\n" for n in a["nodes"])
        if "Węzły — uwagi" in secs:
            out += secs.pop("Węzły — uwagi") + "\n"
    if a.get("edges"):
        out += "\n## Krawędzie\n| Z | Do | Etykieta |\n|---|---|---|\n"
        out += "".join(f"| {e['from']} | {e['to']} | {e.get('label', '')} |\n" for e in a["edges"])
        if "Krawędzie — uwagi" in secs:
            out += secs.pop("Krawędzie — uwagi") + "\n"
    for h, body in secs.items():
        out += f"\n## {h}\n{body}\n"
    if a.get("acceptance"):
        out += "\n## Kryteria akceptacji\n" + "".join(f"- {x}\n" for x in a["acceptance"])
    return out


def run(project) -> str:
    kb = load_kb(project.kb_dir)
    views: Path = project.path("kb.views")
    views.mkdir(parents=True, exist_ok=True)
    m = kb["manifest"]
    g = m.get("game", {})
    w = lambda name, src, body: (views / name).write_text(HEADER.format(src=src) + body, encoding="utf-8", newline="\n")

    idx = f"# {g.get('short', '')} {g.get('rules_version', '')} — baza wiedzy o zasadach\n\n"
    idx += "| Kolekcja | Liczba | Widok |\n|---|---|---|\n"
    for k, f in [("rules", "reguly.md"), ("terms", "definicje.md"), ("tables", "tabele.md"), ("procedures", "procedury.md"),
                 ("relations", "zaleznosci.md"), ("ambiguities", "niejasnosci.md"), ("changes", "zmiany.md"),
                 ("scenarios", "pytania_kontrolne.md"), ("aids", "pomoce/")]:
        idx += f"| {k} | {len(kb[k])} | [{f}]({f}) |\n"
    for key, title in [("interpretation_protocol", "Protokół interpretacji"), ("warnings", "Ostrzeżenia"), ("analysis", "Metadane analizy")]:
        if m.get(key):
            idx += f"\n## {title}\n{m[key]}\n"
    w("INDEX.md", "kb/manifest.yaml", idx)

    body = ""
    for ch in kb["chapters"]:
        body += f"\n## {ch['chapter']['title']}\n\n" + "\n".join(rule_md(r) for r in ch.get("rules", []))
    w("reguly.md", "kb/rules/*.yaml", f"# Reguły atomowe\n{body}")

    from .store import read_yaml
    tf = read_yaml(project.kb_dir / "terms.yaml") or {}
    body = "| EN | PL | Typ | Definicja | Gdzie zdef. | Użycie |\n|---|---|---|---|---|---|\n" + "\n".join(term_row(t) for t in kb["terms"])
    if tf.get("confusables"):
        body += "\n\n## Pary łatwe do pomylenia\n" + "\n".join(
            "- " + (c.get("text") or " | ".join(f"{k}: {v}" for k, v in c.items())) for c in tf["confusables"])
    w("definicje.md", "kb/terms.yaml", "# Definicje terminów\n\n" + body + "\n")
    w("tabele.md", "kb/tables.yaml", "# Tabele i liczby\n\n" + "\n".join(table_md(t) for t in kb["tables"]))
    pf = read_yaml(project.kb_dir / "procedures.yaml") or {}
    w("procedury.md", "kb/procedures.yaml", "# Procedury\n\n" + (pf.get("legend", "") + "\n\n") + "\n".join(proc_md(p) for p in kb["procedures"]))
    body = "| Z | Do | Typ | Status | Uwagi |\n|---|---|---|---|---|\n" + "".join(
        f"| {r['from']} | {r['to']} | {r['type']} | {r.get('status', '')} | {r.get('note', r.get('when', ''))} |\n" for r in kb["relations"])
    notes = project.kb_dir / "notes" / "dependencies.md"
    if notes.exists():
        body += "\n\n---\n\n" + notes.read_text(encoding="utf-8")
    w("zaleznosci.md", "kb/relations.yaml + kb/notes/dependencies.md", "# Zależności (graf relacji)\n\n" + body)
    groups, body = None, ""
    for a in kb["ambiguities"]:
        if a.get("group") != groups:
            groups = a.get("group")
            body += f"\n## {groups}\n\n"
        body += amb_md(a) + "\n"
    w("niejasnosci.md", "kb/ambiguities.yaml", "# Niejasności\n" + body)
    cf = read_yaml(project.kb_dir / "changes.yaml") or {}
    body = "| ID | Miejsce | Zmiana | Skutek | Reguły |\n|---|---|---|---|---|\n" + "".join(
        f"| {c['id']} | {c.get('place', '')} | {c.get('change', '')} | {c.get('effect', '')} | {c.get('rules', '')} |\n" for c in kb["changes"])
    w("zmiany.md", "kb/changes.yaml", "# Zmiany\n\n" + body + "\n" + cf.get("notes", "") + "\n")
    w("pytania_kontrolne.md", "kb/scenarios.yaml", "# Pytania kontrolne\n\n" + "\n".join(scen_md(q) for q in kb["scenarios"]))
    (views / "pomoce").mkdir(exist_ok=True)
    for a in kb["aids"]:
        (views / "pomoce" / (Path(a["_file"]).stem + ".md")).write_text(HEADER.format(src=a["_file"]) + aid_md(a), encoding="utf-8", newline="\n")
    return f"views -> {views}"
